version: "3"
services:
  web-server:
    build:
      dockerfile: php.dockerfile
      context: .
    restart: always
    volumes:
      - "./LaravelBet/:/var/www/html/"
    ports:
      - 8080:80
    links:
      - mariadb

  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: tiaspbiqe2r
      MYSQL_DATABASE: university
    volumes:
      - mysql-data:/var/lib/mysql
      - "./uni.sql:/tmp/uni.sql"

  app:
    build:
      dockerfile: app.Dockerfile
      context: .
    volumes:
      - "./LaravelBet/:/var/www/"

volumes:
  mysql-data:
  user-data-ftp: